### ISSUE TITLE
ERROR: Too many messages queued

### ISSUE THREAD

**Issue by az-z** [s00500/ESPUI#75] opened 2020-05-18 02:20 UTC
hello,

If no client is connected to the esp32(ESPUI) for about 2-3 minutes, the serial produces "ERROR: Too many messages queued" continuously.
it appears the callbacks are still working...
 I suspect this is a general underlying problem, but to reproduce - use "tab" example.

**Comment by s00500** [comment] 2020-06-01 16:23
Did you test this on ESP8266 or ESP32 ?

**Comment by az-z** [comment] 2020-06-01 16:36
This is on esp32 dev board.

**Comment by s00500** [comment] 2020-06-01 16:41
ok two more questions: did you start the ui and connect a client then disconnect ? or just start it without connection ?
Also are you using the hotspot or existing wifi ?

**Comment by az-z** [comment] 2020-06-01 16:47
No wifi network,  just started as a hotspot and connected to it from my
laptop (1 connection only).
I noticed that there are no messages if i keep on using gui.but if i dont
do anything from client, gui(?) Starts spilling the messages after
some time. (1-3 minutes).

**Comment by az-z** [comment] 2020-06-28 19:03
@s00500 ,
 the following may or may not be assosiated with with bug.
But the network performance of this board is piss poor, when it is connected to a router ( 6 feet/2m away):
ping from the laptop:

```
From 192.168.1.5 icmp_seq=1031 Destination Host Unreachable
64 bytes from 192.168.1.14: icmp_seq=1039 ttl=255 time=566 ms
64 bytes from 192.168.1.14: icmp_seq=1045 ttl=255 time=502 ms
64 bytes from 192.168.1.14: icmp_seq=1053 ttl=255 time=1357 ms
64 bytes from 192.168.1.14: icmp_seq=1054 ttl=255 time=335 ms
64 bytes from 192.168.1.14: icmp_seq=1062 ttl=255 time=1149 ms
64 bytes from 192.168.1.14: icmp_seq=1063 ttl=255 time=127 ms
From 192.168.1.5 icmp_seq=1069 Destination Host Unreachable
From 192.168.1.5 icmp_seq=1070 Destination Host Unreachable
From 192.168.1.5 icmp_seq=1071 Destination Host Unreachable
From 192.168.1.5 icmp_seq=1072 Destination Host Unreachable
```

![image](https://user-images.githubusercontent.com/5010397/85955930-117abc80-b950-11ea-8cdd-b5f53c3a7722.png)

at the same time, the ESPUI is _not_ running. It is built into the code of the application, but i do not start it. 
The only code i have running is :


```

void setup() {
	Serial.begin(115200);
	delay(3000);
	esp_log_level_set("*", ESP_LOG_VERBOSE);
//	Create event Group for use by all tasks
	eventGroup = xEventGroupCreate(); //check if NULL NOT returned.
	if (eventGroup == NULL) {
		printf("Event group was not created \n");
		Serial.println("Event group was not created");
	}

	if (loadConfiguration(filename,config) != true) {
		init_config();
	};

	Serial.println("Starting Network ....");
	Start_Net();

```
where "loadConfiguration" parses and loads SSID/pass from the SPIFF stored json file.

**Comment by chamroeunbm** [comment] 2021-03-21 03:54
same issue on my esp32. use it and close browser, then queue error occurs

**Comment by Lagodish** [comment] 2021-09-04 21:41
Same

**Comment by iangray001** [comment] 2022-01-19 20:11
Can people reproduce this issue on the latest commit? I've never been able to reproduce it on either the 8266 or ESP32.

**Comment by garudaonekh** [comment] 2022-01-20 03:23
> Can people reproduce this issue on the latest commit? I've never been able to reproduce it on either the 8266 or ESP32.

I am away from my esp32 controller for now. But as far as I can remember, you can open the ESPUI web page and switch to another tab in the browser, and come back to it after a few minutes.

**Comment by iangray001** [comment] 2022-01-20 18:33
Yes I've been trying this. I've tried from various clients and I can't make it do it. Maybe it has been fixed in the intermediate.

**Closed** 2022-01-20 18:36 UTC
Labels: bug

**Comment by az-z** [comment] 2022-01-20 18:41
Sorry.  I suspended the project i used espui some time ago.

**Comment by VikingVoltage** [comment] 2024-04-08 15:58
> Can people reproduce this issue on the latest commit? I've never been able to reproduce it on either the 8266 or ESP32.

Yes. I can reproduce this consistently via two different methods. 

A) I find if I am sending websocket data too frequently, say less than <30ms between sends, the error will consistently show up. 

B) Using the ESP32 as an Access Point, and the client disconnects with the AP, the error message starts to appear immediately. This can happen if I am connected to the ESP32 AP with two devices such as my phone and the computer. If both are connected to the AP, then turn one of those device's WiFi off, the error message immediately appears. While it is outputting that error message, it is still sending data to the device that remains connected to the AP. 

I'm using ESP32 Dev Module, with PlatformIO on VS Code. My library in platformio.ini is esphome/ESPAsyncWebServer-esphome @ ^3.1.0

The ESP32 will eventually reset if the error message persists for too long. So I do checks to see if I have any websocket connections before sending any data. I also check to see if I have any WiFi connections on the AP before sending data.

**Comment by VikingVoltage** [comment] 2024-04-18 02:21
This is to follow up my previous post, as I did a bit of troubleshooting to find the source of the problem. I am unable to create a solution.

I am using ESP32 as WiFi Access Point. I connect to it with iPhone and Macbook and use a webapp with the websocket to interact with it.

Why is this error a problem? Because not addressing it can cause the ESP32 to reboot.

The error is produced here:
AsyncWebSocket.cpp
Line 554 
```
if(_messageQueue.length() >= WS_MAX_QUEUED_MESSAGES){
      ets_printf("ERROR: Too many messages queued\n"); 
```

The problem seems to lie with the websocketserver not checking to see if the message queue is full (per client) before sending data. Once the message queue is full, the error is produced and will never resolve. Increasing the WS_MAX_QUEUED_MESSAGES can prevent the error in one case, which I'll explain shortly, but does not address the real issue.

AsyncWebSocket.h
Line 28 
`#define WS_MAX_QUEUED_MESSAGES 32  //default is 32`

I can produce the error these ways:

Case A: Connect a device to via WiFi to ESP32's Access Point and websocket is established. Device's WiFi is presumably scanning or doing some other task that causes the websocketserver's message queue for that client to start increasing. 

Case B: Connect a device to via WiFi to ESP32's Access Point and websocket is established, disconnect WiFi on the device.

The standard WiFi library ESPAsyncWebServer-espHome relies on doesn't have any event handlers (that I know of). So this means you have to manually check WiFi.status(), and WiFi.softAPgetStationNum() to see how many WiFi clients are connected. There is no way of knowing if a client disconnects, or if the WiFi connection experiencing an interruption.

I am using webSocket.textAll(jsonString) to broadcast data to any client connected. The function for this is:
AsyncWebSocket.h
Line 946
```
void AsyncWebSocket::textAll(AsyncWebSocketMessageBuffer * buffer){
  if (!buffer) return;
  buffer->lock();
  for(const auto& c: _clients){
    if(c->status() == WS_CONNECTED){    <--No check to see if queue is full
        c->text(buffer);
    }
  }
  buffer->unlock();
  _cleanBuffers();
}

```
So, let's talk about Case A: 
When the device's WiFi is presumably scanning for other networks, or doing some other task that pauses it's WiFi for a short duration (1 second?), the message queue for the websocket client will start to increment for each time data is trying to be sent during that WiFi pause. If you're sending data very frequently, say 40 times/sec (25ms interval), the message queue will have grown to 40 which would have exceeded the default WS_MAX_QUEUED_MESSAGES of 32, the error message will be triggered. If that error message gets triggered, it will never resolve. I assume it could be resolved if when checking if the message queue was full, to clear the message queue. But there is no code in place to do this.  For this case, one could increase WS_MAX_QUEUED_MESSAGES to a high enough value to anticipate the 1 or 2 second WiFi pause, estimating how many messages would be expected to queue during that time. But what happens if the WiFi pause was longer? Changing the WS_MAX_QUEUED_MESSAGES is not the only thing one should do to be safe.

Ok, now on to Case B:
Regardless of the interval time at which data is being sent to the client, if the client disconnects its WiFi, the websocketserver never has a chance to properly close the connection, and the websocketclient remains with the status of being connected "WS_CONNECTED". In the code above of textAll(), it checks to see if the client's status is WS_CONNECTED, and if so, send it data. Because theres' not WiFi connection, the messages will start to queue up, eventually reaching WS_MAX_QUEUED_MESSAGES and triggering the error message. 

I suspect users with projects that are not sending data frequently find that their ESP32 'randomly' reboots. If a user was connected and they walked out of WiFi range to grab lunch, at some point, the ESP32 will reboot while they're munching on a ham and cheese sandwich and when they get back they wonder what happened.

**Comment by VikingVoltage** [comment] 2024-04-18 12:56
I appears impossible to close a websocket client manually that has no WiFi connection as the client's status persists as WS_CONNECTED.  If you follow the library's client->close() path, at least for me, it seems that whatever path I chose (using different parameters), it always needs to communicate with the client in order to close it, but without WiFi connection, it can't communicate with it, so it remains in a WS_CONNECTED state. 

AsyncWebSocket.cpp
```
void AsyncWebSocket::cleanupClients(uint16_t maxClients)
{
  if (count() > maxClients){
    _clients.front()->close();
  }
}
```
webSocket.cleaunupClients() removes the oldest client first. Simply a first in first out. But even then, if the first client has no WiFi, it's status is still WS_CONNECTED, and the following close() will render useless. 

Instead, of blindly removing the oldest client, it should check and remove any problem clients, because the oldest client may still have a good connection. The easiest/fastest check would be to remove any clients with a full Q.

**Comment by EmbeddedDevver** [comment] 2025-03-29 11:09
Am I correct that in the end there is no solution except, prevent WiFi being paused too much and increase the buffer?

**Comment by MartinMueller2003** [comment] 2025-03-29 14:02
Thats pretty much it.
