### ISSUE TITLE
Value changes not propagated to other clients

### ISSUE THREAD

**Issue by ESherlockP32** [s00500/ESPUI#260] opened 2023-10-06 10:11 UTC
Let me first thank you for your great library, I really love working with it.
My problem is a minor issue: when more than one devices are connected to my esp32 and e.g. a slider is changed on one device the changed slider position is not propagated automatically to the other devices. When the page is reloaded the new slider position is shown correctly. Is there a workaround?

Thanks in advance.

**Comment by iangray001** [comment] 2023-10-06 10:54
This is supposed to work. Are you sure you are on the latest version of the software?

**Comment by ESherlockP32** [comment] 2023-10-06 12:30
It worked for me in a project i made about a year ago if I remember correctly.
I reinstalled ESPUI version 2.2.2 today and my arduino-esp32 version was latly updated to 2.0.14.

**Comment by MartinMueller2003** [comment] 2023-10-09 13:03
I think I may know what is wrong. 
@s00500 Is there a target max number of clients to be supported?

**Comment by ESherlockP32** [comment] 2023-10-10 05:42
I didn't set a max number of clients in my code. Is there a default one?

**Comment by MartinMueller2003** [comment] 2023-10-10 11:36
No there is not. I am trying to find out if there is a reasonable number to support. The problem is that there is only a single flag indicating that a value has changed and that flag does not indicate which clients need to be updated so as soon as one client gets updated, then none of the rest will. Guess which client gets updated first?

**Comment by s00500** [comment] 2023-10-14 18:30
> I think I may know what is wrong. @s00500 Is there a target max number of clients to be supported?

Not really, at least there should not be limits in the code

**Comment by MartinMueller2003** [comment] 2023-10-14 18:38
OK. I have a pull mechanism designed.

**Comment by s00500** [comment] 2023-11-03 15:02
@MartinMueller2003 do you need more input here ?

**Comment by MartinMueller2003** [comment] 2023-11-03 15:10
Nope. I have a version that mostly works. I am testing with fragmented controls and seeing an issue.

**Comment by MartinMueller2003** [comment] 2023-11-09 16:08
Fixed in PR: Changes to support keeping multiple Browser Clients in sync #264

**Closed** 2024-07-15 18:00 UTC
